### ISSUE TITLE
Use = instead of => for construction

### ISSUE THREAD

**Issue by davidanthoff** [blackrock/NamedTuples.jl#12]
@mdcfrancis I have a whole bunch of suggestions for changes that would help [Query.jl](https://github.com/davidanthoff/Query.jl) enormously. [Query.jl](https://github.com/davidanthoff/Query.jl) depends heavily on NamedTuples (heck, it wouldn't exist without NamedTuples). I'll post each suggestion as a separate issue. I'm mainly looking for feedback whether you would consider these changes, I could probably implement them as PRs myself if you agree.

The first suggestion is to change the construction syntax from:

``` julia
@NT( a => 1, b => "hello")
```

to

``` julia
@NT( a = 1, b = "hello")
```

The main benefit would be less typing... People will construct very, very many NamedTuples in Query.jl, and anything that makes constructing NamedTuples simpler would help.

It would also make things cleaner in combination with another recommendation I have, I'll point that out once the other issue is open.

I'm not sure how concerned you are about backwards compat, but if such a breaking change is a problem, it should be fairly simply to phase this in over two release cycles, i.e. have one release where the old syntax throws a deprecation warning, but both new and old syntax are supported, and then the old syntax goes away in the next release.

**Comment by davidanthoff** [comment]
In combination with #13, this would also make it easier to construct a NamedTuple with elements of type ``Pair`` and automatic names:
````julia
a = 1
b = 2
@NT(a=>b)
````
would construct a NamedTuple with one automatically named member of type ``Pair{Int64,Int64}``.

**Comment by JeffBezanson** [comment]
+1 for this. Also, in the syntax `a => b` both `a` and `b` are usually evaluated, while in keyword argument syntax `a = b` the `a` is not evaluated, which is also the meaning here.
