### ISSUE TITLE
NamedTuples are no longer type stable

### ISSUE THREAD

**Issue by davidanthoff** [blackrock/NamedTuples.jl#20]
The following
````julia
foo() = @NT(a=1)
````
is no longer type-stable, if I try ``@code_warntype foo()``. Previous versions were type-stable for this.

@JeffBezanson I think this must have been caused by one of your recent commits? Any chance you could look at this? [Query]() completely breaks if that is not type-stable.

**Comment by JeffBezanson** [comment]
I get this output:

```
julia> @code_warntype foo()
Variables:
  #self#::#foo

Body:
  begin 
      return $(Expr(:invoke, MethodInstance for NamedTuples._NT_a(::Int64), :(NamedTuples._NT_a), 1))
  end::NamedTuples._NT_a{Int64}
```

What do you get?

**Comment by JeffBezanson** [comment]
Aha, works on 0.6 but not on 0.5.

**Comment by davidanthoff** [comment]
If v2.0.0 is type stable on 0.5 and v3.0.0 is type stable on 0.6 I should probably be fine. I'll have another look tomorrow.

**Comment by davidanthoff** [comment]
Ok, I can use v2.0.0 on julia 0.5, and v3.0.0 on julia 0.6. Maybe the easiest would be to just say v2.0.0 is the last version to support julia 0.5, and make v3.0.0 and up julia 0.6 only? Doesn't seem worth spending a lot of time fixing this for 0.5 at this point...

**Comment by JeffBezanson** [comment]
Yes that sounds fine.

**Comment by mdcfrancis** [comment]
I will merge and tag

**Comment by mdcfrancis** [comment]
Ah sorry I see what you did - great

**Comment by mdcfrancis** [comment]
Closing with the release-v2 branch we should be good
