### ISSUE TITLE
nfield(x::DataType)

### ISSUE THREAD

**Issue by matthieugomez** [blackrock/NamedTuples.jl#33]
I think that `nfield(x::DataType)` returns a wrong result on the current master version with Julia 0.6. 

```julia
using NamedTuples
x = @NT(a = 0.0, b = 0.0, c = 0.0)
nfields(NamedTuples._NT_a_b_c)
# returns 2 while I expected 3
```
The registered version on Metadata with Julia 0.5 returns 3, which is the answer I expected

**Comment by shashi** [comment]
```julia
julia> using NamedTuples

julia> x = @NT(a = 0.0, b = 0.0, c = 0.0)
(a = 0.0, b = 0.0, c = 0.0)

julia> nfields(NamedTuples._NT_a_b_c)
2

# however:
julia> nfields(typeof(x))
3
```
Not sure if this is a bug. cc @JeffBezanson

**Comment by JeffBezanson** [comment]
Yes, this is not specific to NamedTuples. Currently it's giving 2 since a UnionAll type has 2 components. I'm not sure what to do in this case, but it should be addressed in base julia.

**Comment by matthieugomez** [comment]
See discussion in https://github.com/JuliaLang/julia/pull/22350
