### ISSUE TITLE
deprecation warnings

### ISSUE THREAD

**Issue by malmaud** [blackrock/NamedTuples.jl#4]
On master, I'm seeing

```
WARNING: names(v) is deprecated, use fieldnames(v) instead.
```

**Comment by mdcfrancis** [comment]
Thanks I'll have a look and push a fix.

**Comment by mdcfrancis** [comment]
This got swept into one of my fixes today. I've not tagged yet. Pending some further testing.

**Comment by davidanthoff** [comment]
Any chance a new version could be tagged? The current one gives deprecation warnings on julia 0.4. Thanks!

**Comment by mdcfrancis** [comment]
Working on it

**Comment by mdcfrancis** [comment]
I have submitted the METADATA change

**Comment by mdcfrancis** [comment]
You should be good now, sorry for the delay.
